set_hsv_advanced_old:
  target:
    entity:
      domain: light
  fields:
    hsv_command_string:
      example: "+20,100,20 2 :setHueAnim"
      required: true
      selector:
        text:
    hsv_command_string2:
      example: "+20,100,20 2 :setHueAnim"
      required: true
      selector:
        text:

animation:
  name: Run an animation on the controller
  description: >
    Sets a sequence of colors using a list of HSV values.
    The list must not be empty.
  target:
    entity:
      domain: light
  fields:
    anim_definition:
      name: HSV Color List
      description: "A list of HSV objects. Each value can be 0-100 or a relative string like '+1000'."
      required: true
      selector:
        object:
          label_field: name
          description_field: percentage
          multiple: true
          fields:
            name:
              label: Name
              selector:
                text:
            percentage:
              label: Percentage
              selector:
                number:
                  unit_of_measurement: "%"
            queue_policy:
              label: Queueing Policy
              selector:
                select:
                  options:
                    - value: back
                      label: Back
                    - value: front
                      label: Front
                    - value: front_reset
                      label: Front Reset
                    - value: single
                      label: Single

pause:
  name: Pause
  description: >
    Pauses the current HSV animation on all or some channels.
  fields:
    all_channels:
      name: All Channels
      description: "Cancel all channels"
      required: true
    channel_h:
      name: Hue
      description: "Cancel hue channel animation"
      required: false

