animation_cli_hsv:
  name: Run an HSV animation on the controller using CLI
  description: >
    Use the command line syntax to define a HSV animation.
  target:
    entity:
      domain: light
  fields:
    anim_definition_command:
      name: Command string to run one or more animation
      description: "A command string the command string syntax"
      required: true
      example: "120,0,5 5"
      selector:
        text:

animation_cli_rgbww:
  name: Run an RGB(WW) animation on the controller using CLI
  description: >
    Use the command line syntax to define an RGB(WW) animation.
  target:
    entity:
      domain: light
  fields:
    anim_definition_command:
      name: Command string to run one or more animation
      description: "A command string the command string syntax"
      required: true
      example: "103,0,5,453 5"
      selector:
        text:

animation_hsv:
  name: Run an animation on the controller using the HSV channels
  description: >
    Sets a sequence of colors using a list of HSV values.
    The list must not be empty.
  target:
    entity:
      domain: light
  fields:
    anim_definition:
      name: Animation Commands
      description: "A list of command objects."
      required: true
      selector:
        object:
          label_field: hue
          description_field: transition_mode
          multiple: true
          fields:
            hue:
              label: Hue
              selector:
                text:
            saturation:
              label: Saturation
              selector:
                text:
            brightness:
              label: Brightness
              selector:
                text:
            color_temp_kelvin:
              label: Color Temperature (Kelvin)
              selector:
                text:
            transition_mode:
              label: Transition Mode
              selector:
                select:
                  options:
                    - label: Time
                      value: time
                    - label: Speed
                      value: speed
            transition_value:
              label: Transition Value (Time/Speed)
              selector:
                number:
                  mode: box
                  step: 100
                  unit_of_measurement: "ms or speed"
            stay:
              label: Stay Time
              selector:
                number:
                  mode: box
                  step: 100
                  unit_of_measurement: "ms"
            queue_policy:
              label: Queue Policy
              required: false
              selector:
                select:
                  options:
                    - label: Single
                      value: single
                    - label: Back
                      value: back
                    - label: Front
                      value: front
                    - label: Front Reset
                      value: front_reset
                  mode: dropdown
            requeue:
              label: Requeue when finished
              selector:
                boolean:


animation_rgbww:
  name: Run an animation on the controller using the RGB(WW) channles
  description: >
    Sets a sequence of colors using a list of RGB(WW) values.
    The list must not be empty.
  target:
    entity:
      domain: light
  fields:
    anim_definition:
      name: Animation Commands
      description: "A list of command objects."
      required: true
      selector:
        object:
          label_field: hue
          description_field: transition_mode
          multiple: true
          fields:
            red:
              label: Red
              selector:
                text:
            green:
              label: Green
              selector:
                text:
            blue:
              label: Blue
              selector:
                text:
            cw:
              label: Cold White
              selector:
                text:
            ww:
              label: Warm White
              selector:
                text:
            transition_mode:
              label: Transition Mode
              selector:
                select:
                  options:
                    - label: Time
                      value: time
                    - label: Speed
                      value: speed
            transition_value:
              label: Transition Value (Time/Speed)
              selector:
                number:
                  mode: box
                  step: 100
                  unit_of_measurement: "ms or speed"
            stay:
              label: Stay Time
              selector:
                number:
                  mode: box
                  step: 100
                  unit_of_measurement: "ms"
            queue_policy:
              label: Queue Policy
              required: false
              selector:
                select:
                  options:
                    - label: Single
                      value: single
                    - label: Back
                      value: back
                    - label: Front
                      value: front
                    - label: Front Reset
                      value: front_reset
                  mode: dropdown
            requeue:
              label: Requeue when finished
              selector:
                boolean:

control_channel:
  name: Control Channel
  description: Sends a control command to an entity's channel.

  # Definition of the fields the user can interact with in the UI.
  fields:
    # The 'command' field is rendered as a dropdown menu.
    command:
      name: Command
      description: The command to be executed.
      required: true
      example: "pause"
      # The 'select' selector creates the dropdown menu.
      selector:
        select:
          # The options available in the dropdown.
          # These must exactly match the values in your Voluptuous schema.
          options:
            - "pause"
            - "stop"
            - "continue"

    channels:
      name: Target Channels
      description: Deselect any channels you do not want the command to apply to.
      required: true

      default:
        - "hue"
        - "saturation"
        - "value"
        - "color_temp"

      selector:
        select:
          multiple: true
          options:
            - "hue"
            - "saturation"
            - "value"
            - "color_temp"
  target:
    entity:
      domain: light