set_hsv_advanced_old:
  target:
    entity:
      domain: light
  fields:
    hsv_command_string:
      example: "+20,100,20 2 :setHueAnim"
      required: true
      selector:
        text:
    hsv_command_string2:
      example: "+20,100,20 2 :setHueAnim"
      required: true
      selector:
        text:

animation_cli:
  name: Run an animation on the controller
  description: >
    Sets a sequence of colors using a list of HSV values.
    The list must not be empty.
  target:
    entity:
      domain: light
  fields:
    anim_definition_command:
      name: Command string to run one or more animation
      description: "A command string the command string syntax"
      required: true
      example: "120,0,5 5"
      selector:
        text:

animation:
  name: Run an animation on the controller
  description: >
    Sets a sequence of colors using a list of HSV values.
    The list must not be empty.
  target:
    entity:
      domain: light
  fields:
    anim_definition:
      name: Animation Commands
      description: "A list of command objects."
      required: true
      selector:
        object:
          label_field: hue
          description_field: transition_mode
          multiple: true
          fields:
            hue:
              label: Hue
              selector:
                text:
            saturation:
              label: Saturation
              selector:
                text:
            brightness:
              label: Brightness
              selector:
                text:
            color_temp_kelvin:
              label: Color Temperature (Kelvin)
              selector:
                text:
            transition_mode:
              label: Transition Mode
              selector:
                select:
                  options:
                    - label: Time
                      value: time
                    - label: Speed
                      value: speed
            transition_value:
              label: Transition Value (Time/Speed)
              selector:
                number:
                  mode: slider
                  step: 100
                  unit_of_measurement: "ms or speed"
            stay:
              label: Stay Time
              selector:
                number:
                  mode: slider
                  step: 100
                  unit_of_measurement: "ms"
            queue_policy:
              label: Queue Policy
              required: false
              selector:
                select:
                  options:
                    - label: Single
                      value: single
                    - label: Back
                      value: back
                    - label: Front
                      value: front
                    - label: Front Reset
                      value: front_reset
                  mode: dropdown
            requeue:
              label: Requeue when finished
              selector:
                boolean:

animation_bak:
  name: Run an animation on the controller
  description: >
    Sets a sequence of colors using a list of HSV values.
    The list must not be empty.
  target:
    entity:
      domain: light
  fields:
    anim_definition:
      name: HSV Color List
      description: "A list of HSV objects. Each value can be 0-100 or a relative string like '+1000'."
      required: true
      selector:
        object:
          label_field: name
          description_field: percentage
          multiple: true
          fields:
            hue:
              label: Hue
              selector:
                text:
            saturation:
              label: Saturation
              selector:
                text:
            brightness:
              label: Brightness
              selector:
                text:
            transition_mode:
              label: Transition Mode
              selector:
                select:
                  options:
                    - label: Time
                      value: time
                    - label: Speed
                      value: speed
            transition_value:
              label: Transition Value (Time/Speed)
              selector:
                number:
                  mode: slider
                  step: 100
                  unit_of_measurement: "ms or speed"
            stay:
              label: Stay Time
              selector:
                number:
                  mode: slider
                  step: 100
                  unit_of_measurement: "ms"
            queue_policy:
              label: Queue Policy
              selector:
                select:
                  options:
                    - label: Single
                      value: single
                    - label: Back
                      value: back
                    - label: Front
                      value: front
                    - label: Front Reset
                      value: front_reset
                  mode: dropdown
            requeue:
              label: Requeue
              selector:
                boolean:

pause:
  name: Pause
  description: >
    Pauses the current HSV animation on all or some channels.
  fields:
    all_channels:
      name: All Channels
      description: "Cancel all channels"
      required: true
    channel_h:
      name: Hue
      description: "Cancel hue channel animation"
      required: false

